### ISSUE TITLE
Calling methods via instantiate API

### ISSUE THREAD

**Issue by rsokl** [mit-ll-responsible-ai/hydra-zen#205]
This is just a prototype. We can use zen-wrappers to let people specify a method call via instantiate:

```python
from hydra_zen import builds, instantiate

def outer(Target, *, mthd_name, mthd_args, mthd_kwargs):
    
    def wrapper(*args, **kwargs):
        return getattr(Target(*args, **kwargs), mthd_name)(*mthd_args, **mthd_kwargs)
    return wrapper

def call_method(mthd_name, *mthd_args, **mthd_kwargs):
    return builds(
        outer,
        mthd_args=mthd_args,
        mthd_name=mthd_name,
        mthd_kwargs=mthd_kwargs,
        populate_full_signature=True,
        zen_partial=True
    )
```

```python
class A:
    def __init__(self, x):
        self.x = x
    def x_plus_y(self, y):
        return self.x + y
```

```python
>>> instantiate(builds(A, x=-11, zen_wrappers=call_method("x_plus_y", y=2)))
-9
```

I can't say I love this form factor, or the readability of this. Specifying the method via its name (a string) is not very zen. I would want to see if I can make the yaml more legible:
```
_target_: hydra_zen.funcs.zen_processing
_zen_target: __main__.A
_zen_wrappers:
  _target_: hydra_zen.funcs.zen_processing
  _zen_target: __main__.call_method
  _zen_partial: true
  mthd_name: x_plus_y
  'y': 2
x: -11
```

Some things for us to consider:
- Would it be worthwhile for us to provide users with this sort of wrapper?
- Can the wrapper be designed to handle class & instance & static methods?
- Can we avoid requiring the method be specified by name (string)?
- Is there some sort of optional validation API that we can expose for zen-wrappers in general? So that `builds(A, x=-11, zen_wrappers=call_method("x_plus_y", y=2))` can validate that the method call will be valid upon instantiation?
