### ISSUE TITLE
Design Question: Omit default hydra-fields from `builds`?

### ISSUE THREAD

**Issue by rsokl** [mit-ll-responsible-ai/hydra-zen#35]
Currently, `builds` populates all hydra-relevant fields in the dataclass even if those fields are the default values that hydra would infer if they were missing.

## Potential Change / Pros of this

Our current behavior

```python
>>> print(to_yaml(builds(dict)))
_target_: builtins.dict
_recursive_: true
_convert_: none
```
We could omit `_recursive_` and `_convert_`  when these values are the defaults (and thus implicitly rely on hydra's default behavior), and thus end up with a cleaner yaml. 

```python
>>> print(to_yaml(builds(dict)))
_target_: builtins.dict
```

This matters more at-scale.

```
ExpConfig = builds(
    gradient_descent,
    optim=builds(SGD, lr=0.3, momentum=0.0, hydra_partial=True),
    landscape_fn=just(parabaloid),
    starting_xy=(-1.5, 0.5),
    num_steps=20,
)
print(to_yaml(ExpConfig))
_target_: __main__.gradient_descent
_recursive_: true
_convert_: none
optim:
  _target_: hydra_zen.funcs.partial
  _partial_target_:
    _target_: hydra_zen.funcs.get_obj
    path: torch.optim.sgd.SGD
  _recursive_: true
  _convert_: none
  lr: 0.3
  momentum: 0.0
landscape_fn:
  _target_: hydra_zen.funcs.get_obj
  path: __main__.parabaloid
starting_xy:
- -1.5
- 0.5
num_steps: 20
```

could become..

```
_target_: __main__.gradient_descent
optim:
  _target_: hydra_zen.funcs.partial
  _partial_target_:
    _target_: hydra_zen.funcs.get_obj
    path: torch.optim.sgd.SGD
  lr: 0.3
  momentum: 0.0
landscape_fn:
  _target_: hydra_zen.funcs.get_obj
  path: __main__.parabaloid
starting_xy:
- -1.5
- 0.5
num_steps: 20
```
which is tidier.

We would potentially implement the signature with `None` as the defaults `builds(..., hydra_recursive=None, hydra_convert=None)`. Here, fields are only omitted if they are `None`; any user-specified value, even if it is the default, would be included. This enables users to force these fields to appear in the dataclass (although it would be somewhat cumbersome to do so..)

## Cons

- The yamls are less explicit. Users need to know what hydra's default behaviors are. Although I do wonder how much users actually _need_ to know about / adjust these  at the yaml level
- The aforementioned discussion of using `None` as  the default values makes our documentation and behavior more complicated. We have to make `None` ultimately default to whatever the default hydra behavior is... which presumably is only available via "word of mouth" (i.e. docs). And we have to explain to the user why `hydra_recursive=None` exhibits the same behavior of `hydra_recursive=True` - i.e. answer the questions "well why isn't the default just `True` then?"
- Omitting these fields make inheritance via `builds_bases` a bit more complicated; we have to fill in these fields, even if they are the default values, if any of the parents have these fields parents. Otherwise we would mistakenly inherit that parent's fields.

Ultimately what this all comes down to: how much do we care about making yamls more succinct?
