### ISSUE TITLE
Examples of running hydra sweeper plugins

### ISSUE THREAD

**Issue by behzadk** [mit-ll-responsible-ai/hydra-zen#563]
Hello!

Really enjoying using hydra-zen moving over from standard hydra. Could you help me with getting sweeper plugins running?

Using standard hydra my config yaml would look something like this for running the optuna plugin:
```yaml
defaults:
  - _self_
  - user: default
  - data: diabetes
  - model: sklearn_random_forest_regressor
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

# Metric that we want to optimize for
optimize_metrics:
  - val_MeanSquaredError

hydra:
  sweeper:
    sampler:
      seed: 21
    direction: minimize # We want to minimize val_loss
    study_name: test
    storage: null
    n_trials: 50
    n_jobs: 1

    params:
      model.n_estimators: range(100, 700)
      model.max_features: interval(0.05, 1.00)
      model.max_depth: choice(2, 4, 8, 16, 32, 64, 128, 256, 512)
      model.min_samples_split: choice(2, 5, 10)
```

I can get a multirun gridsearch up and running as below, 
```python
def train_random_forest_grid_search():
    config = store.get_entry("example_group", "example_config_name")    
    task_function = zen(run_train)


    overrides = ["model.n_estimators=10,100",
                 "model.max_features=0.1,0.25,0.5,0.75,1.0",
                 "model.max_depth=2,4,8,16",
                 "model.min_samples_split=2,5,10"]

    # Run gridsearch
    (jobs,) = launch(
        config['node'],
        task_function,
        overrides=overrides,
        multirun=True
    )
```
I haven't figured out how to use multirun with a plugin to set the overrides. Would appreciate it if you can point me to some examples!
